### ISSUE TITLE
Create a Mouse Class

### ISSUE THREAD

**Issue by 51lv3str1** [TeamUroboros/Uroboros-Engine#12]
Similar to the Key class, a Mouse class is a listener that is responsible for controlling if an action associated with the mouse is being executed.

* NOBUTTON = 0;
* BUTTON1 = 1;
* BUTTON2 = 2;
* BUTTON3 = 3.

constructors should be LEFT_BUTTON(1), RIGHT_BUTTON(2), WHEEL_BUTTON(3), MOUSE_MOVED(0), MOUSE_ENTERED(0), MOUSE_EXITED(0);

**Comment by gguzman89** [comment]
[Mouse Listener](https://docs.oracle.com/javase/8/docs/api/java/awt/event/MouseListener.html)

[Mouse Motion Listener](https://docs.oracle.com/javase/8/docs/api/java/awt/event/MouseMotionListener.html)
